"""add_health_models

Revision ID: 5a2d50784a40
Revises: eaff71712afa
Create Date: 2026-09-12 16:32:32.296053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2d50784a40'
down_revision: Union[str, Sequence[str], None] = 'eaff71712afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('repository_scan_id', sa.String(length=36), nullable=False),
    sa.Column('quality_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('security_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('dependency_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('architecture_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('security_score', sa.Float(), nullable=False),
    sa.Column('dependency_score', sa.Float(), nullable=False),
    sa.Column('architecture_score', sa.Float(), nullable=False),
    sa.Column('maintainability_score', sa.Float(), nullable=False),
    sa.Column('testing_score', sa.Float(), nullable=False),
    sa.Column('technical_debt_hours', sa.Float(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('explanations', sa.JSON(), nullable=True),
    sa.Column('debt_breakdown', sa.JSON(), nullable=True),
    sa.Column('fix_first', sa.JSON(), nullable=True),
    sa.Column('weights_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['architecture_analysis_id'], ['architecture_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dependency_analysis_id'], ['dependency_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quality_analysis_id'], ['quality_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_scan_id'], ['project_scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_analysis_id'], ['security_analyses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_analyses_architecture_analysis_id'), 'health_analyses', ['architecture_analysis_id'], unique=False)
    op.create_index(op.f('ix_health_analyses_dependency_analysis_id'), 'health_analyses', ['dependency_analysis_id'], unique=False)
    op.create_index(op.f('ix_health_analyses_id'), 'health_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_health_analyses_project_id'), 'health_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_health_analyses_quality_analysis_id'), 'health_analyses', ['quality_analysis_id'], unique=False)
    op.create_index(op.f('ix_health_analyses_repository_scan_id'), 'health_analyses', ['repository_scan_id'], unique=False)
    op.create_index(op.f('ix_health_analyses_security_analysis_id'), 'health_analyses', ['security_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_analyses_security_analysis_id'), table_name='health_analyses')
    op.drop_index(op.f('ix_health_analyses_repository_scan_id'), table_name='health_analyses')
    op.drop_index(op.f('ix_health_analyses_quality_analysis_id'), table_name='health_analyses')
    op.drop_index(op.f('ix_health_analyses_project_id'), table_name='health_analyses')
    op.drop_index(op.f('ix_health_analyses_id'), table_name='health_analyses')
    op.drop_index(op.f('ix_health_analyses_dependency_analysis_id'), table_name='health_analyses')
    op.drop_index(op.f('ix_health_analyses_architecture_analysis_id'), table_name='health_analyses')
    op.drop_table('health_analyses')
    # ### end Alembic commands ###
