"""add_ai_explanation_models

Revision ID: 5dc71aca6df2
Revises: 5a2d50784a40
Create Date: 2026-09-12 16:50:39.299280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc71aca6df2'
down_revision: Union[str, Sequence[str], None] = '5a2d50784a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_explanations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('issue_category', sa.String(length=50), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('potential_impact', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('developer_action', sa.Text(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_explanations_id'), 'ai_explanations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_explanations_issue_category'), 'ai_explanations', ['issue_category'], unique=False)
    op.create_index(op.f('ix_ai_explanations_issue_id'), 'ai_explanations', ['issue_id'], unique=False)
    op.create_index(op.f('ix_ai_explanations_issue_type'), 'ai_explanations', ['issue_type'], unique=False)
    op.create_index(op.f('ix_ai_explanations_project_id'), 'ai_explanations', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_explanations_project_id'), table_name='ai_explanations')
    op.drop_index(op.f('ix_ai_explanations_issue_type'), table_name='ai_explanations')
    op.drop_index(op.f('ix_ai_explanations_issue_id'), table_name='ai_explanations')
    op.drop_index(op.f('ix_ai_explanations_issue_category'), table_name='ai_explanations')
    op.drop_index(op.f('ix_ai_explanations_id'), table_name='ai_explanations')
    op.drop_table('ai_explanations')
    # ### end Alembic commands ###
