"""add_dependency_models

Revision ID: b0e3322f3b5b
Revises: ba9b6d894758
Create Date: 2026-09-12 13:56:24.984448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e3322f3b5b'
down_revision: Union[str, Sequence[str], None] = 'ba9b6d894758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_dependencies', sa.Integer(), nullable=True),
    sa.Column('direct_dependencies', sa.Integer(), nullable=True),
    sa.Column('transitive_dependencies', sa.Integer(), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('outdated_count', sa.Integer(), nullable=True),
    sa.Column('vulnerable_count', sa.Integer(), nullable=True),
    sa.Column('unknown_count', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_analyses_id'), 'dependency_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_dependency_analyses_project_id'), 'dependency_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_dependency_analyses_scan_id'), 'dependency_analyses', ['scan_id'], unique=False)
    op.create_table('project_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('manifest_file', sa.String(length=500), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('declared_version', sa.String(length=100), nullable=True),
    sa.Column('resolved_version', sa.String(length=100), nullable=True),
    sa.Column('dependency_type', sa.String(length=50), nullable=True),
    sa.Column('latest_version', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('vulnerability_count', sa.Integer(), nullable=True),
    sa.Column('advisories', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['dependency_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_dependencies_analysis_id'), 'project_dependencies', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_project_dependencies_dependency_type'), 'project_dependencies', ['dependency_type'], unique=False)
    op.create_index(op.f('ix_project_dependencies_ecosystem'), 'project_dependencies', ['ecosystem'], unique=False)
    op.create_index(op.f('ix_project_dependencies_id'), 'project_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_project_dependencies_manifest_file'), 'project_dependencies', ['manifest_file'], unique=False)
    op.create_index(op.f('ix_project_dependencies_name'), 'project_dependencies', ['name'], unique=False)
    op.create_index(op.f('ix_project_dependencies_project_id'), 'project_dependencies', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_dependencies_status'), 'project_dependencies', ['status'], unique=False)
    op.create_table('dependency_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('package_name', sa.String(length=150), nullable=False),
    sa.Column('manifest_file', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('vulnerability_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['dependency_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dependency_id'], ['project_dependencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_issues_analysis_id'), 'dependency_issues', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_dependency_issues_category'), 'dependency_issues', ['category'], unique=False)
    op.create_index(op.f('ix_dependency_issues_dependency_id'), 'dependency_issues', ['dependency_id'], unique=False)
    op.create_index(op.f('ix_dependency_issues_id'), 'dependency_issues', ['id'], unique=False)
    op.create_index(op.f('ix_dependency_issues_issue_type'), 'dependency_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_dependency_issues_project_id'), 'dependency_issues', ['project_id'], unique=False)
    op.create_index(op.f('ix_dependency_issues_severity'), 'dependency_issues', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dependency_issues_severity'), table_name='dependency_issues')
    op.drop_index(op.f('ix_dependency_issues_project_id'), table_name='dependency_issues')
    op.drop_index(op.f('ix_dependency_issues_issue_type'), table_name='dependency_issues')
    op.drop_index(op.f('ix_dependency_issues_id'), table_name='dependency_issues')
    op.drop_index(op.f('ix_dependency_issues_dependency_id'), table_name='dependency_issues')
    op.drop_index(op.f('ix_dependency_issues_category'), table_name='dependency_issues')
    op.drop_index(op.f('ix_dependency_issues_analysis_id'), table_name='dependency_issues')
    op.drop_table('dependency_issues')
    op.drop_index(op.f('ix_project_dependencies_status'), table_name='project_dependencies')
    op.drop_index(op.f('ix_project_dependencies_project_id'), table_name='project_dependencies')
    op.drop_index(op.f('ix_project_dependencies_name'), table_name='project_dependencies')
    op.drop_index(op.f('ix_project_dependencies_manifest_file'), table_name='project_dependencies')
    op.drop_index(op.f('ix_project_dependencies_id'), table_name='project_dependencies')
    op.drop_index(op.f('ix_project_dependencies_ecosystem'), table_name='project_dependencies')
    op.drop_index(op.f('ix_project_dependencies_dependency_type'), table_name='project_dependencies')
    op.drop_index(op.f('ix_project_dependencies_analysis_id'), table_name='project_dependencies')
    op.drop_table('project_dependencies')
    op.drop_index(op.f('ix_dependency_analyses_scan_id'), table_name='dependency_analyses')
    op.drop_index(op.f('ix_dependency_analyses_project_id'), table_name='dependency_analyses')
    op.drop_index(op.f('ix_dependency_analyses_id'), table_name='dependency_analyses')
    op.drop_table('dependency_analyses')
    # ### end Alembic commands ###
