"""add_security_models

Revision ID: ba9b6d894758
Revises: fcc7d458cd27
Create Date: 2026-09-12 10:36:07.213158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9b6d894758'
down_revision: Union[str, Sequence[str], None] = 'fcc7d458cd27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_issues', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=True),
    sa.Column('high_count', sa.Integer(), nullable=True),
    sa.Column('medium_count', sa.Integer(), nullable=True),
    sa.Column('low_count', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_analyses_id'), 'security_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_security_analyses_project_id'), 'security_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_security_analyses_scan_id'), 'security_analyses', ['scan_id'], unique=False)
    op.create_table('security_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('issue_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('symbol_name', sa.String(length=150), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['security_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_issues_analysis_id'), 'security_issues', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_security_issues_category'), 'security_issues', ['category'], unique=False)
    op.create_index(op.f('ix_security_issues_confidence'), 'security_issues', ['confidence'], unique=False)
    op.create_index(op.f('ix_security_issues_file_path'), 'security_issues', ['file_path'], unique=False)
    op.create_index(op.f('ix_security_issues_id'), 'security_issues', ['id'], unique=False)
    op.create_index(op.f('ix_security_issues_issue_type'), 'security_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_security_issues_project_id'), 'security_issues', ['project_id'], unique=False)
    op.create_index(op.f('ix_security_issues_severity'), 'security_issues', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_issues_severity'), table_name='security_issues')
    op.drop_index(op.f('ix_security_issues_project_id'), table_name='security_issues')
    op.drop_index(op.f('ix_security_issues_issue_type'), table_name='security_issues')
    op.drop_index(op.f('ix_security_issues_id'), table_name='security_issues')
    op.drop_index(op.f('ix_security_issues_file_path'), table_name='security_issues')
    op.drop_index(op.f('ix_security_issues_confidence'), table_name='security_issues')
    op.drop_index(op.f('ix_security_issues_category'), table_name='security_issues')
    op.drop_index(op.f('ix_security_issues_analysis_id'), table_name='security_issues')
    op.drop_table('security_issues')
    op.drop_index(op.f('ix_security_analyses_scan_id'), table_name='security_analyses')
    op.drop_index(op.f('ix_security_analyses_project_id'), table_name='security_analyses')
    op.drop_index(op.f('ix_security_analyses_id'), table_name='security_analyses')
    op.drop_table('security_analyses')
    # ### end Alembic commands ###
