"""add_project_analysis_snapshots_table

Revision ID: c0ce2b75d58e
Revises: 5dc71aca6df2
Create Date: 2026-09-12 17:39:29.560234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ce2b75d58e'
down_revision: Union[str, Sequence[str], None] = '5dc71aca6df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_analysis_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('repository_scan_id', sa.String(length=36), nullable=True),
    sa.Column('quality_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('security_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('dependency_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('architecture_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('health_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('security_score', sa.Float(), nullable=False),
    sa.Column('dependency_score', sa.Float(), nullable=False),
    sa.Column('architecture_score', sa.Float(), nullable=False),
    sa.Column('maintainability_score', sa.Float(), nullable=False),
    sa.Column('testing_score', sa.Float(), nullable=False),
    sa.Column('technical_debt_hours', sa.Float(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('critical_security_count', sa.Integer(), nullable=False),
    sa.Column('high_security_count', sa.Integer(), nullable=False),
    sa.Column('high_complexity_count', sa.Integer(), nullable=False),
    sa.Column('long_functions_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_blocks_count', sa.Integer(), nullable=False),
    sa.Column('total_dependencies', sa.Integer(), nullable=False),
    sa.Column('vulnerable_dependencies_count', sa.Integer(), nullable=False),
    sa.Column('outdated_dependencies_count', sa.Integer(), nullable=False),
    sa.Column('architecture_nodes_count', sa.Integer(), nullable=False),
    sa.Column('architecture_edges_count', sa.Integer(), nullable=False),
    sa.Column('architecture_cycles_count', sa.Integer(), nullable=False),
    sa.Column('file_manifest', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['architecture_analysis_id'], ['architecture_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dependency_analysis_id'], ['dependency_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['health_analysis_id'], ['health_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quality_analysis_id'], ['quality_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_scan_id'], ['project_scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_analysis_id'], ['security_analyses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_analysis_snapshots_architecture_analysis_id'), 'project_analysis_snapshots', ['architecture_analysis_id'], unique=False)
    op.create_index(op.f('ix_project_analysis_snapshots_created_at'), 'project_analysis_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_analysis_snapshots_dependency_analysis_id'), 'project_analysis_snapshots', ['dependency_analysis_id'], unique=False)
    op.create_index(op.f('ix_project_analysis_snapshots_health_analysis_id'), 'project_analysis_snapshots', ['health_analysis_id'], unique=False)
    op.create_index(op.f('ix_project_analysis_snapshots_id'), 'project_analysis_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_project_analysis_snapshots_project_id'), 'project_analysis_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_analysis_snapshots_quality_analysis_id'), 'project_analysis_snapshots', ['quality_analysis_id'], unique=False)
    op.create_index(op.f('ix_project_analysis_snapshots_repository_scan_id'), 'project_analysis_snapshots', ['repository_scan_id'], unique=False)
    op.create_index(op.f('ix_project_analysis_snapshots_security_analysis_id'), 'project_analysis_snapshots', ['security_analysis_id'], unique=False)
    op.create_index(op.f('ix_project_analysis_snapshots_version_number'), 'project_analysis_snapshots', ['version_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_analysis_snapshots_version_number'), table_name='project_analysis_snapshots')
    op.drop_index(op.f('ix_project_analysis_snapshots_security_analysis_id'), table_name='project_analysis_snapshots')
    op.drop_index(op.f('ix_project_analysis_snapshots_repository_scan_id'), table_name='project_analysis_snapshots')
    op.drop_index(op.f('ix_project_analysis_snapshots_quality_analysis_id'), table_name='project_analysis_snapshots')
    op.drop_index(op.f('ix_project_analysis_snapshots_project_id'), table_name='project_analysis_snapshots')
    op.drop_index(op.f('ix_project_analysis_snapshots_id'), table_name='project_analysis_snapshots')
    op.drop_index(op.f('ix_project_analysis_snapshots_health_analysis_id'), table_name='project_analysis_snapshots')
    op.drop_index(op.f('ix_project_analysis_snapshots_dependency_analysis_id'), table_name='project_analysis_snapshots')
    op.drop_index(op.f('ix_project_analysis_snapshots_created_at'), table_name='project_analysis_snapshots')
    op.drop_index(op.f('ix_project_analysis_snapshots_architecture_analysis_id'), table_name='project_analysis_snapshots')
    op.drop_table('project_analysis_snapshots')
    # ### end Alembic commands ###
