"""add_scan_and_file_models

Revision ID: c69d24241edd
Revises: c77b73f1f0e1
Create Date: 2026-09-12 00:23:34.827159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69d24241edd'
down_revision: Union[str, Sequence[str], None] = 'c77b73f1f0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('total_directories', sa.Integer(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('total_code_lines', sa.Integer(), nullable=True),
    sa.Column('total_blank_lines', sa.Integer(), nullable=True),
    sa.Column('total_comment_lines', sa.Integer(), nullable=True),
    sa.Column('test_files_count', sa.Integer(), nullable=True),
    sa.Column('config_files_count', sa.Integer(), nullable=True),
    sa.Column('doc_files_count', sa.Integer(), nullable=True),
    sa.Column('languages_summary', sa.JSON(), nullable=True),
    sa.Column('categories_summary', sa.JSON(), nullable=True),
    sa.Column('directory_tree', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_scans_id'), 'project_scans', ['id'], unique=False)
    op.create_index(op.f('ix_project_scans_project_id'), 'project_scans', ['project_id'], unique=False)
    op.create_table('project_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('code_lines', sa.Integer(), nullable=True),
    sa.Column('blank_lines', sa.Integer(), nullable=True),
    sa.Column('comment_lines', sa.Integer(), nullable=True),
    sa.Column('is_binary', sa.Boolean(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=True),
    sa.Column('is_config', sa.Boolean(), nullable=True),
    sa.Column('is_doc', sa.Boolean(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_files_id'), 'project_files', ['id'], unique=False)
    op.create_index(op.f('ix_project_files_project_id'), 'project_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_files_scan_id'), 'project_files', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_files_scan_id'), table_name='project_files')
    op.drop_index(op.f('ix_project_files_project_id'), table_name='project_files')
    op.drop_index(op.f('ix_project_files_id'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_index(op.f('ix_project_scans_project_id'), table_name='project_scans')
    op.drop_index(op.f('ix_project_scans_id'), table_name='project_scans')
    op.drop_table('project_scans')
    # ### end Alembic commands ###
